<a href="https://colab.research.google.com/github/nigamkumar3435-spec/codsoft-Credit-Card-Fraud-Detection/blob/main/Project_2_Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset to a Pandas DataFrame

credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
#first 5 rows of the dataset

credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11954,20631,1.504204,-0.411728,0.200090,-0.778753,-0.442232,-0.119677,-0.782660,-0.165178,0.691819,...,-0.136231,-0.217274,-0.143260,-1.057332,0.529188,-0.235062,-0.012089,0.000905,9.00,0.0
11955,20636,1.134994,0.096340,0.277921,0.319692,0.742800,1.611803,-0.458649,0.390012,1.424541,...,-0.395605,-0.743542,0.222256,-1.859104,-0.109777,0.279049,0.012398,-0.009090,0.99,0.0
11956,20638,-6.305012,3.944886,-4.707362,1.539602,-3.934785,-1.730565,-2.104936,3.843447,0.863458,...,0.073140,-0.039935,-0.108896,0.691434,-0.261979,-0.447540,0.212900,-0.031021,89.99,0.0
11957,20638,1.161960,-0.398297,1.123732,-0.474237,-1.226667,-0.519325,-0.804179,0.070134,3.262926,...,-0.121191,0.097255,0.050903,0.330479,0.315692,-0.712765,0.073836,0.028055,11.85,0.0
11958,20642,1.291096,-0.226628,0.708386,-0.719236,-0.659099,-0.273757,-0.612042,-0.111488,3.032258,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#dataset_informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11959 entries, 0 to 11958
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    11959 non-null  int64
 1   V1      11959 non-null  float64
 2   V2      11959 non-null  float64
 3   V3      11959 non-null  float64
 4   V4      11959 non-null  float64
 5   V5      11959 non-null  float64
 6   V6      11959 non-null  float64
 7   V7      11959 non-null  float64
 8   V8      11959 non-null  float64
 9   V9      11959 non-null  float64
 10  V10     11959 non-null  float64
 11  V11     11959 non-null  float64
 12  V12     11959 non-null  float64
 13  V13     11959 non-null  float64
 14  V14     11959 non-null  float64
 15  V15     11959 non-null  float64
 16  V16     11959 non-null  float64
 17  V17     11959 non-null  float64
 18  V18     11959 non-null  float64
 19  V19     11959 non-null  float64
 20  V20     11958 non-null  float64
 21  V21     11958 non-null  float64
 22  V22     11958 non-null  float64
 23  V23     11958 non-null  float64
 24  V24     11958 non-null  float64
 25  V25     11958 non-null  float64
 26  V26     11958 non-null  float64
 27  V27     11958 non-null  float64
 28  V28     11958 non-null  float64
 29  Amount  11958 non-null  float64
 30  Class   11958 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 2.8 MB

In [ ]:
#check the number of missing values in each columns
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#distribution of legit transaction & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    11906
1.0       52
Name: count, dtype: int64

This dataset is highly unbalanced

In [ ]:
#0-normal transaction
#1-fraudulent transaction

#separating the data for analysis

legit=credit_card_data[credit_card_data.Class == 0]
fraud=credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(11906, 31)
(52, 31)

In [ ]:
#statistical measures fo the data
legit.Amount.describe()

count    11906.000000
mean        62.198127
std        177.379105
min          0.000000
25%          5.292500
50%         15.950000
75%         50.000000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      52.000000
mean       97.724808
std       321.188775
min         0.000000
25%         1.000000
50%         1.000000
75%         1.772500
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,7993.389048,-0.200839,0.259753,0.929229,0.255987,-0.076685,0.149326,-0.097364,-0.053087,0.927305,...,0.020836,-0.063076,-0.154427,-0.032369,0.018962,0.105861,0.061825,0.005330,0.000012,62.198127
1.0,11569.615385,-3.769104,4.258027,-8.202329,6.396396,-2.342431,-1.990562,-5.740207,0.950650,-2.729769,...,0.411236,0.305259,-0.021762,-0.340563,-0.406311,-0.139505,0.306967,0.692927,0.059751,97.724808

Under-Sampling

In [ ]:
# Build a sample dataset containing similar distribution of normal transactions and Fraudulent transactions
# Number of Fraudulent transactions --> 492

legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [ ]:
new_dataset=pd.concat([legit_sample,fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3613,3090,-0.997331,0.040240,1.942636,-0.625598,-0.249134,-0.662369,0.307702,0.060638,0.363065,...,0.172738,0.576809,0.015423,0.501296,-0.088208,0.984639,0.261656,0.193929,77.72,0.0
2335,1874,-2.482454,2.308903,0.321264,-0.926674,-1.113441,-0.906290,-0.848198,-1.634175,-0.463774,...,2.442128,-0.725129,0.360794,0.737415,-0.326198,0.678931,-0.798529,-0.294767,12.99,0.0
9043,12610,1.198241,0.369492,0.306401,0.652273,0.117844,-0.040892,-0.187974,0.016767,1.061042,...,-0.379745,-0.840888,0.117125,-0.406625,0.137718,0.088180,-0.036727,0.007554,0.89,0.0
6140,7080,1.200184,0.344835,1.249012,2.677709,-0.231716,0.774449,-0.671989,0.149029,1.464438,...,-0.303280,-0.465964,-0.066618,-0.682319,0.409066,-0.019789,0.014889,0.019117,0.00,0.0
9125,12886,-2.097094,-0.503764,0.481407,-2.255937,-0.325686,1.170120,-0.991313,1.168754,-1.568041,...,-0.044250,0.462918,0.221650,-1.078500,0.127244,-0.161769,-0.325427,-0.144792,48.00,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
10897,18690,-15.398845,7.472324,-19.026912,11.165526,-6.893856,-2.120937,-14.913330,-0.721214,-7.175097,...,-2.444884,0.727495,-0.345078,-0.981749,0.995271,0.816762,2.262942,-1.178063,1.0,1.0
11343,19762,-14.179165,7.421370,-21.405836,11.927512,-7.974281,-2.202710,-15.471612,-0.356595,-6.380125,...,-2.366836,1.130955,0.991153,-1.033132,-0.327179,0.634693,2.171905,-1.395288,1.0,1.0
11710,20011,-14.724627,7.875157,-21.872317,11.906170,-8.348734,-2.262846,-15.833443,0.077874,-6.356833,...,-2.362345,1.099557,1.037199,-1.036359,-0.254777,0.642343,2.161129,-1.401282,1.0,1.0
11841,20332,-15.271362,8.326581,-22.338591,11.885313,-8.721334,-2.324307,-16.196419,0.512882,-6.333685,...,-2.356896,1.068019,1.085617,-1.039797,-0.182006,0.649921,2.149247,-1.406811,1.0,1.0
11880,20451,-15.819179,8.775997,-22.804686,11.864868,-9.092361,-2.386893,-16.560368,0.948349,-6.310658,...,-2.350634,1.036362,1.136051,-1.043414,-0.108923,0.657437,2.136424,-1.411945,1.0,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     52
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,8311.534553,-0.229499,0.298441,0.906605,0.286324,-0.095591,0.119175,-0.078511,-0.05582,1.024554,...,-0.016608,-0.057565,-0.128656,-0.015312,-0.010534,0.126391,0.064098,-0.028779,0.001558,56.441809
1.0,11569.615385,-3.769104,4.258027,-8.202329,6.396396,-2.342431,-1.990562,-5.740207,0.95065,-2.729769,...,0.411236,0.305259,-0.021762,-0.340563,-0.406311,-0.139505,0.306967,0.692927,0.059751,97.724808

Splitting the data into Features and Targets

In [ ]:
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

In [ ]:
print(X)

        Time         V1        V2         V3         V4        V5        V6  \
3613    3090  -0.997331  0.040240   1.942636  -0.625598 -0.249134 -0.662369
2335    1874  -2.482454  2.308903   0.321264  -0.926674 -1.113441 -0.906290
9043   12610   1.198241  0.369492   0.306401   0.652273  0.117844 -0.040892
6140    7080   1.200184  0.344835   1.249012   2.677709 -0.231716  0.774449
9125   12886  -2.097094 -0.503764   0.481407  -2.255937 -0.325686  1.170120
...      ...        ...       ...        ...        ...       ...       ...
10897  18690 -15.398845  7.472324 -19.026912  11.165526 -6.893856 -2.120937
11343  19762 -14.179165  7.421370 -21.405836  11.927512 -7.974281 -2.202710
11710  20011 -14.724627  7.875157 -21.872317  11.906170 -8.348734 -2.262846
11841  20332 -15.271362  8.326581 -22.338591  11.885313 -8.721334 -2.324307
11880  20451 -15.819179  8.775997 -22.804686  11.864868 -9.092361 -2.386893

              V7        V8        V9  ...       V20       V21       V22  \
3613    0.307702  0.060638  0.363065  ...  0.354144  0.172738  0.576809
2335   -0.848198 -1.634175 -0.463774  ... -0.865409  2.442128 -0.725129
9043   -0.187974  0.016767  1.061042  ... -0.129259 -0.379745 -0.840888
6140   -0.671989  0.149029  1.464438  ... -0.174504 -0.303280 -0.465964
9125   -0.991313  1.168754 -1.568041  ... -0.892383 -0.044250  0.462918
...          ...       ...       ...  ...       ...       ...       ...
10897 -14.913330 -0.721214 -7.175097  ...  1.111502 -2.444884  0.727495
11343 -15.471612 -0.356595 -6.380125  ...  1.002764 -2.366836  1.130955
11710 -15.833443  0.077874 -6.356833  ...  0.996469 -2.362345  1.099557
11841 -16.196419  0.512882 -6.333685  ...  0.993121 -2.356896  1.068019
11880 -16.560368  0.948349 -6.310658  ...  0.992279 -2.350634  1.036362

            V23       V24       V25       V26       V27       V28  Amount
3613   0.015423  0.501296 -0.088208  0.984639  0.261656  0.193929   77.72
2335   0.360794  0.737415 -0.326198  0.678931 -0.798529 -0.294767   12.99
9043   0.117125 -0.406625  0.137718  0.088180 -0.036727  0.007554    0.89
6140  -0.066618 -0.682319  0.409066 -0.019789  0.014889  0.019117    0.00
9125   0.221650 -1.078500  0.127244 -0.161769 -0.325427 -0.144792   48.00
...         ...       ...       ...       ...       ...       ...     ...
10897 -0.345078 -0.981749  0.995271  0.816762  2.262942 -1.178063    1.00
11343  0.991153 -1.033132 -0.327179  0.634693  2.171905 -1.395288    1.00
11710  1.037199 -1.036359 -0.254777  0.642343  2.161129 -1.401282    1.00
11841  1.085617 -1.039797 -0.182006  0.649921  2.149247 -1.406811    1.00
11880  1.136051 -1.043414 -0.108923  0.657437  2.136424 -1.411945    1.00

[544 rows x 30 columns]

In [ ]:
print(Y)

3613     0.0
2335     0.0
9043     0.0
6140     0.0
9125     0.0
        ...
10897    1.0
11343    1.0
11710    1.0
11841    1.0
11880    1.0
Name: Class, Length: 544, dtype: float64

Split the data into Training Data and Testing Data

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(544, 30) (435, 30) (109, 30)

Model Training

In [ ]:
# LOGISTIC REGRESSION

model=LogisticRegression()

In [ ]:
#training the Logistic Regression Model with Training Data
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

In [ ]:
# ACCURACY SCORE

#accuracy on training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
print('Accuracy on Training data:',training_data_accuracy)

Accuracy on Training data: 0.9885057471264368

In [ ]:
#accuracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [ ]:
print('Accuracy on Test data:',test_data_accuracy)

Accuracy on Test data: 1.0